# Generated by Django 4.0.5 on 2022-08-04 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='...', max_length=120, verbose_name='nomi')),
                ('image', models.ImageField(blank=True, upload_to='%d-%H-%m/', verbose_name='rasm')),
                ('about', models.TextField(verbose_name='malumot')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='.', max_length=120, verbose_name='nomi')),
                ('file', models.FileField(blank=True, null=True, upload_to='certificate/%d-%H', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
    ]
