# Generated by Django 4.0.5 on 2022-08-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
